/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AiRouteImport } from './routes/ai'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as DashboardSplitwiseIndexRouteImport } from './routes/dashboard/splitwise/index'
import { Route as DashboardReminderIndexRouteImport } from './routes/dashboard/reminder/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardLoanIndexRouteImport } from './routes/dashboard/loan/index'
import { Route as DashboardIncomeIndexRouteImport } from './routes/dashboard/income/index'
import { Route as DashboardExpenseIndexRouteImport } from './routes/dashboard/expense/index'
import { Route as DashboardSplitwiseProjectIdRouteImport } from './routes/dashboard/splitwise/$projectId'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardLoanProjectIdIndexRouteImport } from './routes/dashboard/loan/$projectId/index'
import { Route as DashboardLoanProjectIdSingleLoanIdRouteImport } from './routes/dashboard/loan/$projectId/single/$loanId'

const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSplitwiseIndexRoute = DashboardSplitwiseIndexRouteImport.update({
  id: '/dashboard/splitwise/',
  path: '/dashboard/splitwise/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReminderIndexRoute = DashboardReminderIndexRouteImport.update({
  id: '/dashboard/reminder/',
  path: '/dashboard/reminder/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/dashboard/projects/',
  path: '/dashboard/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLoanIndexRoute = DashboardLoanIndexRouteImport.update({
  id: '/dashboard/loan/',
  path: '/dashboard/loan/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIncomeIndexRoute = DashboardIncomeIndexRouteImport.update({
  id: '/dashboard/income/',
  path: '/dashboard/income/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardExpenseIndexRoute = DashboardExpenseIndexRouteImport.update({
  id: '/dashboard/expense/',
  path: '/dashboard/expense/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSplitwiseProjectIdRoute =
  DashboardSplitwiseProjectIdRouteImport.update({
    id: '/dashboard/splitwise/$projectId',
    path: '/dashboard/splitwise/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLoanProjectIdIndexRoute =
  DashboardLoanProjectIdIndexRouteImport.update({
    id: '/dashboard/loan/$projectId/',
    path: '/dashboard/loan/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardLoanProjectIdSingleLoanIdRoute =
  DashboardLoanProjectIdSingleLoanIdRouteImport.update({
    id: '/dashboard/loan/$projectId/single/$loanId',
    path: '/dashboard/loan/$projectId/single/$loanId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/ai': typeof AiRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/splitwise/$projectId': typeof DashboardSplitwiseProjectIdRoute
  '/dashboard/expense': typeof DashboardExpenseIndexRoute
  '/dashboard/income': typeof DashboardIncomeIndexRoute
  '/dashboard/loan': typeof DashboardLoanIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/reminder': typeof DashboardReminderIndexRoute
  '/dashboard/splitwise': typeof DashboardSplitwiseIndexRoute
  '/dashboard/loan/$projectId': typeof DashboardLoanProjectIdIndexRoute
  '/dashboard/loan/$projectId/single/$loanId': typeof DashboardLoanProjectIdSingleLoanIdRoute
}
export interface FileRoutesByTo {
  '/ai': typeof AiRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/splitwise/$projectId': typeof DashboardSplitwiseProjectIdRoute
  '/dashboard/expense': typeof DashboardExpenseIndexRoute
  '/dashboard/income': typeof DashboardIncomeIndexRoute
  '/dashboard/loan': typeof DashboardLoanIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/reminder': typeof DashboardReminderIndexRoute
  '/dashboard/splitwise': typeof DashboardSplitwiseIndexRoute
  '/dashboard/loan/$projectId': typeof DashboardLoanProjectIdIndexRoute
  '/dashboard/loan/$projectId/single/$loanId': typeof DashboardLoanProjectIdSingleLoanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/ai': typeof AiRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/api/chat': typeof ApiChatRoute
  '/(public)/': typeof publicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/splitwise/$projectId': typeof DashboardSplitwiseProjectIdRoute
  '/dashboard/expense/': typeof DashboardExpenseIndexRoute
  '/dashboard/income/': typeof DashboardIncomeIndexRoute
  '/dashboard/loan/': typeof DashboardLoanIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/reminder/': typeof DashboardReminderIndexRoute
  '/dashboard/splitwise/': typeof DashboardSplitwiseIndexRoute
  '/dashboard/loan/$projectId/': typeof DashboardLoanProjectIdIndexRoute
  '/dashboard/loan/$projectId/single/$loanId': typeof DashboardLoanProjectIdSingleLoanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ai'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/api/chat'
    | '/'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/splitwise/$projectId'
    | '/dashboard/expense'
    | '/dashboard/income'
    | '/dashboard/loan'
    | '/dashboard/projects'
    | '/dashboard/reminder'
    | '/dashboard/splitwise'
    | '/dashboard/loan/$projectId'
    | '/dashboard/loan/$projectId/single/$loanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/api/chat'
    | '/'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/splitwise/$projectId'
    | '/dashboard/expense'
    | '/dashboard/income'
    | '/dashboard/loan'
    | '/dashboard/projects'
    | '/dashboard/reminder'
    | '/dashboard/splitwise'
    | '/dashboard/loan/$projectId'
    | '/dashboard/loan/$projectId/single/$loanId'
  id:
    | '__root__'
    | '/ai'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(auth)/verify-email'
    | '/api/chat'
    | '/(public)/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/splitwise/$projectId'
    | '/dashboard/expense/'
    | '/dashboard/income/'
    | '/dashboard/loan/'
    | '/dashboard/projects/'
    | '/dashboard/reminder/'
    | '/dashboard/splitwise/'
    | '/dashboard/loan/$projectId/'
    | '/dashboard/loan/$projectId/single/$loanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AiRoute: typeof AiRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  ApiChatRoute: typeof ApiChatRoute
  publicIndexRoute: typeof publicIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  DashboardSplitwiseProjectIdRoute: typeof DashboardSplitwiseProjectIdRoute
  DashboardExpenseIndexRoute: typeof DashboardExpenseIndexRoute
  DashboardIncomeIndexRoute: typeof DashboardIncomeIndexRoute
  DashboardLoanIndexRoute: typeof DashboardLoanIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardReminderIndexRoute: typeof DashboardReminderIndexRoute
  DashboardSplitwiseIndexRoute: typeof DashboardSplitwiseIndexRoute
  DashboardLoanProjectIdIndexRoute: typeof DashboardLoanProjectIdIndexRoute
  DashboardLoanProjectIdSingleLoanIdRoute: typeof DashboardLoanProjectIdSingleLoanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/splitwise/': {
      id: '/dashboard/splitwise/'
      path: '/dashboard/splitwise'
      fullPath: '/dashboard/splitwise'
      preLoaderRoute: typeof DashboardSplitwiseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reminder/': {
      id: '/dashboard/reminder/'
      path: '/dashboard/reminder'
      fullPath: '/dashboard/reminder'
      preLoaderRoute: typeof DashboardReminderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/loan/': {
      id: '/dashboard/loan/'
      path: '/dashboard/loan'
      fullPath: '/dashboard/loan'
      preLoaderRoute: typeof DashboardLoanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/income/': {
      id: '/dashboard/income/'
      path: '/dashboard/income'
      fullPath: '/dashboard/income'
      preLoaderRoute: typeof DashboardIncomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/expense/': {
      id: '/dashboard/expense/'
      path: '/dashboard/expense'
      fullPath: '/dashboard/expense'
      preLoaderRoute: typeof DashboardExpenseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/splitwise/$projectId': {
      id: '/dashboard/splitwise/$projectId'
      path: '/dashboard/splitwise/$projectId'
      fullPath: '/dashboard/splitwise/$projectId'
      preLoaderRoute: typeof DashboardSplitwiseProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/loan/$projectId/': {
      id: '/dashboard/loan/$projectId/'
      path: '/dashboard/loan/$projectId'
      fullPath: '/dashboard/loan/$projectId'
      preLoaderRoute: typeof DashboardLoanProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/loan/$projectId/single/$loanId': {
      id: '/dashboard/loan/$projectId/single/$loanId'
      path: '/dashboard/loan/$projectId/single/$loanId'
      fullPath: '/dashboard/loan/$projectId/single/$loanId'
      preLoaderRoute: typeof DashboardLoanProjectIdSingleLoanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AiRoute: AiRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  ApiChatRoute: ApiChatRoute,
  publicIndexRoute: publicIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  DashboardSplitwiseProjectIdRoute: DashboardSplitwiseProjectIdRoute,
  DashboardExpenseIndexRoute: DashboardExpenseIndexRoute,
  DashboardIncomeIndexRoute: DashboardIncomeIndexRoute,
  DashboardLoanIndexRoute: DashboardLoanIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardReminderIndexRoute: DashboardReminderIndexRoute,
  DashboardSplitwiseIndexRoute: DashboardSplitwiseIndexRoute,
  DashboardLoanProjectIdIndexRoute: DashboardLoanProjectIdIndexRoute,
  DashboardLoanProjectIdSingleLoanIdRoute:
    DashboardLoanProjectIdSingleLoanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
